apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sports-store-services
  namespace: sports-store
  labels:
    app.kubernetes.io/part-of: sports-store
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sports-store
  namespaceSelector:
    matchNames:
      - sports-store
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
