{{- range $name, $svc := .Values.services }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sports-store.serviceAccountName" $name }}
  namespace: {{ $.Values.namespace }}
  labels:
    {{- include "sports-store.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
  {{- with $svc.serviceAccount.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ . }}
  {{- end }}
---
{{- end }}
